// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
        // return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyAaLyqjHTH0Bihbgg_7XTa6PlO9_wr6a8M',
  //   appId: '1:330378584606:web:bfcb0b68bd6ee83253840f',
  //   messagingSenderId: '330378584606',
  //   projectId: 'slsproject-d5968',
  //   authDomain: 'slsproject-d5968.firebaseapp.com',
  //   storageBucket: 'slsproject-d5968.appspot.com',
  //   measurementId: 'G-BP6LX4FMCD',
  // );
//'slsproject-d5968.firebaseapp.com'
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6qAFFuBfvzNXikcQbfwPWKoLnfayHkM',
    appId: '1:77680200384:android:daa8b87fb5eff4cf9efb25',
    messagingSenderId: '105509399042',
    projectId: 'chat-ae02a',
    storageBucket: 'movies-d5968.appspot.com',
  );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBsB5Plxk7wpONT-wYdPp2QPkgG8rGW_KY',
  //   appId: '1:330378584606:ios:06025421aec636d153840f',
  //   messagingSenderId: '330378584606',
  //   projectId: 'slsproject-d5968',
  //   storageBucket: 'slsproject-d5968.appspot.com',
  //   iosClientId: '330378584606-f0202ha0larhlalt72ij3sbgt7895g1k.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.sls',
  // );
}